WITH CUSTOMERS AS 
(
    SELECT * FROM {{ ref('Stage_customers') }}
),
ORDERSS AS
(
    SELECT * FROM {{ ref('Stage_orders') }}
),

customer_orders AS (

SELECT C. C_CUSTKEY AS CUTOMER_KEYS,
--O.O_ORDERKEY AS ORDER_KEYS,
COUNT(O.O_ORDERKEY) AS NUMBER,
SUM(O.O_TOTALPRICE) AS TOTAL_PRICE,
O.O_ORDERDATE AS THE_DAY_ORDERED_DATE
FROM CUSTOMERS C 
INNER JOIN ORDERSS O ON C.C_CUSTKEY=O.O_CUSTKEY
GROUP BY CUTOMER_KEYS, THE_DAY_ORDERED_DATE
ORDER BY NUMBER DESC
)

SELECT * FROM customer_orders LIMIT 1000